### ISSUE TITLE
Creating shapes with input and output connections

### ISSUE THREAD

**Issue by shujaatak** [rodydavis/flutter_multi_touch_canvas#1]
Is it possible to create **Node Graph Editor** using **flutter_multi_touch_canvas**?

Any ideas to create inputs and outputs of a shape and connecting shapes together?

**Comment by rodydavis** [comment]
You can also do it with InteractiveViewer. But yeah totally possible, I have wanted to build one

**Comment by rodydavis** [comment]
You could do it all on the canvas with widgets using this. You can create a simple algorithm to build the relationships. 

You could also look at this https://pub.dev/packages/graphview
